[package]
name = "session-man-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
chrono = "0.4.41"
env_logger = "0.11.8"
headless_chrome = { version = "1.0.17", features = ["fetch"] }
log = "0.4.27"
tokio = { version = "1.46.1", features = ["fs", "full", "signal"] }
