[package]
name = "binding"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
serde = "1.0.219"
serde_json = "1.0.141"
protocol = { path = "../protocol" }
config = "0.15.13"
dotenvy = "0.15.7"
